Program options added
MichaelKupriianov/TaskManager pull request #10
Opened 2022-02-07 13:21 UTC by MichaelKupriianov

- -host, -port and --debug options added to client
- -host, -port and --debug options added to server
- --debug option added to main

2022-02-07 13:33 UTC, KharchenkoMaks requested changes

2022-02-07 13:33 UTC, KharchenkoMaks commented on src/client.cpp
> +        FileLogging{"client.log", boost::log::trivial::info};
`(arguments.find("debug") != arguments.end()) ? boost::log::trivial::debug : boost::log::trivial::info`
?

2022-02-07 13:33 UTC, KharchenkoMaks commented on src/main.cpp
> +        FileLogging{"main.log", boost::log::trivial::info};
code repeating?

2022-02-08 10:50 UTC, MichaelKupriianov commented on src/client.cpp
> +        FileLogging{"client.log", boost::log::trivial::info};
Fixed

2022-02-14 13:46 UTC, merged