TaskManager class refactor
MichaelKupriianov/TaskManager pull request #3
Opened 2022-01-24 12:18 UTC by MichaelKupriianov

- Sorting moved to utilities folder
- TasksSortBy enum moved to utilities folder
- bug in TaskManager::Edit method fixed
- code style fixes

2022-01-24 12:24 UTC, KharchenkoMaks commented
> bug in TaskManager::Edit method fixed
maybe it is better to move bug fixing to separate PR?

2022-01-24 12:45 UTC, antonovchtd approved these changes

2022-01-24 14:31 UTC, antonovchtd approved these changes

2022-01-24 16:15 UTC, AntonApraksin requested changes
Lots of files that are not related to PR

2022-01-24 16:15 UTC, AntonApraksin commented on src/utilities/SortingProtoObjects.cpp
> +    if (first.first < second.first) return true;
Maybe `return first.first < second.first;`?

2022-01-25 10:53 UTC, MichaelKupriianov commented on src/utilities/SortingProtoObjects.cpp
> +    if (first.first < second.first) return true;
Fixed

2022-01-25 14:54 UTC, AntonApraksin approved these changes

2022-01-28 14:23 UTC, merged