GRPC transport between client and master added
MichaelKupriianov/TaskManager pull request #7
Opened 2022-01-28 14:55 UTC by MichaelKupriianov

- Create client and server executables
- Proto files for GRPC created
- Class model::GRPCEndPoint added for transport from server side
- Class ui::GRPCEndPoint added for transport from client side

2022-01-28 15:17 UTC, AntonApraksin requested changes

2022-01-28 15:17 UTC, AntonApraksin commented on src/model/GRPCEndPoint.h
> +    explicit GRPCEndPoint(std::shared_ptr<Model> model) : model_{model} {}
Use `std::move` or `const std::shared_ptr<>&`.

2022-01-28 15:18 UTC, MichaelKupriianov commented on src/model/GRPCEndPoint.h
> +    explicit GRPCEndPoint(std::shared_ptr<Model> model) : model_{model} {}
Fixed

2022-01-28 15:19 UTC, AntonApraksin approved these changes

2022-01-30 16:38 UTC, IlliaPlaksa approved these changes

2022-01-31 09:52 UTC, vladimir-moiseiev approved these changes

2022-01-31 11:00 UTC, merged